modLoader="javafml"
loaderVersion="[4,)"
license="Steamcreate2 Mod Custom License"

[[mods]]
modId="steamcore"
logoFile="icon.png"
version="1.0.4"
description='''coremod for steamcore modpack.'''
displayName="Steamcore"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steamcore"
authors="Dseelis"

[[dependencies.steamcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"
#Only on modrinth
#[[dependencies.steamcore]]
#modId = "ftbteams"
#mandatory = true
#versionRange = "2101.1.9"
#ordering = "AFTER"
#side = "BOTH"

#[[dependencies.steamcore]]
#modId = "ftblibrary"
#mandatory = true
#versionRange = "2101.1.30"
#ordering = "AFTER"
#side = "BOTH"

#[[dependencies.steamcore]]
#modId = "ftbquests"
#mandatory = true
#versionRange = "2101.1.21"
#ordering = "AFTER"
#side = "BOTH"

#[[dependencies.steamcore]]
#modId = "ftbfiltersystem"
#mandatory = true
#versionRange = "21.1.4"
#ordering = "AFTER"
#side = "BOTH"

#[[dependencies.steamcore]]
#modId = "ftbxmodcompat"
#mandatory = true
#versionRange = "21.1.7"
#ordering = "AFTER"
#side = "BOTH"

#[[dependencies.steamcore]]
#modId = "ftbchunks"
#mandatory = true
#versionRange = "2101.1.13"
#ordering = "AFTER"
#side = "BOTH"
