modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="steamcore"
logoFile="icon.png"
version="1.0.4"
description='''coremod for steamcore modpack.'''
displayName="Steamcore"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steamcore"
authors="Dseelis"

[[dependencies.steamcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"
